services:
  web:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: barbell-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
      - .env.db
    environment:
      - DATABASE_URL=postgresql+psycopg2://myuser:mypassword@db:5432/myappdb
      - DEBUG=true
    volumes:
      - ./app:/app
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    container_name: barbell-frontend
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
      - ./app/web/static:/app/web/static
      - ./app/services/email/templates:/frontend/compiled_emails
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

volumes:
  postgres_data:
